### ISSUE TITLE
[FEATURE] Quick-reply buttons

### ISSUE THREAD

**Issue by dlassalle** [RocketChat/Apps.Dialogflow#16]
- [ ] Display quick reply buttons from DF response payloads
- [ ] When clicked, it should send `payload` string to DF and display in client as if the user entered it

custom DF payload example
```
{
  "quick_replies": [
    {
      "payload": "Chat with live agent",
      "content_type": "text"
    },
    {
      "content_type": "text",
      "payload": "Not now"
    }
  ]
}
```

**Comment by murtaza98** [comment]
> Display quick reply buttons from DF response payloads
I've added support to parse the `quick_reply` property from the payload and pass it as `attachment` to the message. 

> When clicked, it should send payload string to DF and display in client as if the user entered it
I don't think this is the responsibility of the App, rather it should be handled by the Livechat widget

**Comment by murtaza98** [comment]
Hello, @dlassalle One quick question,
Can u explain the difference between `title` n `payload` property in this payload?
`{
  "quick_replies": [
    {
      "payload": "Chat with live agent",
      "content_type": "text",
      "title": "Chat with live agent"
    },
    {
      "content_type": "text",
      "payload": "Not now",
      "title": "Not now"
    }
  ]
}`

**Comment by murtaza98** [comment]
Hello, @dlassalle One quick question,
Can u explain the difference between `title` n `payload` property in this payload?
`{
  "quick_replies": [
    {
      "payload": "Chat with live agent",
      "content_type": "text",
      "title": "Chat with live agent"
    },
    {
      "content_type": "text",
      "payload": "Not now",
      "title": "Not now"
    }
  ]
}`

**Comment by murtaza98** [comment]
Hello, @dlassalle One quick question,
Can u explain the difference between `title` n `payload` property in this payload?
`{
  "quick_replies": [
    {
      "payload": "Chat with live agent",
      "content_type": "text",
      "title": "Chat with live agent"
    },
    {
      "content_type": "text",
      "payload": "Not now",
      "title": "Not now"
    }
  ]
}`

**Comment by dlassalle** [comment]
@murtaza98 good point - for our current uses we only use text, which doesn't need both fields (there are other options where 'title' is what is displayed to the user as a button, while 'payload' is what is actually sent on clicking)
I'll revise this

**Comment by dlassalle** [comment]
Created issue on client https://github.com/RocketChat/Rocket.Chat.Livechat/issues/437

**Comment by dlassalle** [comment]
Issue resolved
