### ISSUE TITLE
[FEATURE] Add any unrecognized custom payloads as message attachments 

### ISSUE THREAD

**Issue by dlassalle** [RocketChat/Apps.Dialogflow#29]
this should allow for future livechat widget changes to interpret these attachments and act accordingly, without having to update this app each time

this should be able to handle any number of payloads on an intent

**Comment by renatobecker** [comment]
@dlassalle can you please share an example of `unrecognized` payload here?

**Comment by dlassalle** [comment]
an `unrecognized` custom payload meaning any custom payload that the dialogflow app doesnt have some special handling for already (basically any custom payload that isnt quickReplies at the moment)

**Comment by murtaza98** [comment]
We could attach the custom payload to the messages `custom-field` in the app. @renatobecker WDYT?

**Comment by renatobecker** [comment]
> We could attach the custom payload to the messages `custom-field` in the app. @renatobecker WDYT?

No, actually the approach that @dlassalle suggested, based on `attachments`, is the right way to display the custom payloads. This is something achievable, my point is how it would look like, you know?

That's what I'm wondering.

**Comment by dlassalle** [comment]
@renatobecker a couple custom payloads:
```
{
  "disableInputMessage": "Please wait",
  "disableInput": true
}
```
```
{
  "followup": {
    "event": "go_to_b_show_bill--examine_bill",
    "delay": 5000
  }
}
```

**Comment by renatobecker** [comment]
Thanks @dlassalle. 
Okay, my point now is how those payloads would be helpful being displayed as attachments.. they would appear to the final user as well, so wouldn't it be weird? What are your thoughts about that?

**Comment by dlassalle** [comment]
I didnt know that... i assumed attachments were ignored unless specifically handled by something in livechat widget...
im trying to prevent the need for making changes to both DF app and livechat widget for each of these

**Comment by murtaza98** [comment]
Hello, @dlassalle 

The [`IMessageAttachment`](https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/5f6d40458df1bcfa2c23f3fbad4af4f15584b0a4/src/definition/messages/IMessageAttachment.ts#L10) wouldn't allow the app to send any unknown payload.

One possible solution is to send the custom payload within [`customFields`](https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/5f6d40458df1bcfa2c23f3fbad4af4f15584b0a4/src/definition/messages/IMessage.ts#L26) of the message. Then in the Livechat widget, we can retrieve it and perform an action accordingly(like we can disable the input field, etc).

**Comment by dlassalle** [comment]
That sounds fine to me. The sooner we get that in, the better - and I can start having community members implement changes in our livechat fork

**Comment by dlassalle** [comment]
Restructuring this feature, as the UIKit in the works is going to let us do these actions within the app
