### ISSUE TITLE
[FEATURE] Parsing of disable-input payloads

### ISSUE THREAD

**Issue by dlassalle** [RocketChat/Apps.Dialogflow#40]
Until the UIKit is updated, we cant actually implement the disabling of the input, but in the meantime we should define and parse what disable-input payloads look like, and ensure to the best of our ability that they work alongside quick-replies

Example payload format:
```
{
  "disableInput": true,
  "disableInputMessage": "Please select from the provided options"
}
```

**Comment by shubhsherl** [comment]
```
{
  "quickReplies": {
    "options": [{
      "text": "myText"
    },
    {
      "text": "myText 1"
    }],
    "disableInputMessage": "don't reply",
    "disableInput": true,
    "text": "Quick Reply Button Name"
  },
  "text": "Random text inserted here"
}
```
Payload to disable input.
