### ISSUE TITLE
[FEATURE] Option to trigger handover if errors/exception occur

### ISSUE THREAD

**Issue by dlassalle** [RocketChat/Apps.Dialogflow#41]
If we run into a technical issue in the middle of a chat, or right from the start, we should have an option to trigger a hand off to the live agent department to take over.
An important thing is to stop doing so if the chat is transferred back to the bot, since we dont want an infinite loop of being transferred due to errors on either side

Example errors:
failure to reach DF
incorrect credentials when calling DF endpoints

**Comment by PrajvalRaval** [comment]
Will be working on this 👍
