### ISSUE TITLE
Deployment error: Direct installation of an App is disabled.

### ISSUE THREAD

**Issue by samirjac** [RocketChat/Apps.Dialogflow#54]
Hi,

When I try to perform the deployment according to the manual the error appears ...

![image](https://user-images.githubusercontent.com/79640634/109149292-21000e80-7746-11eb-99ac-09071b551cc4.png)

**Comment by Shailesh351** [comment]
Hey @samirjac,

You will need to enable setting to install apps that are not from the rocket chat marketplace.
`Admin Setting -> General -> Apps -> Enable development mode`

**Comment by samirjac** [comment]
Thanks....

It worked!!!
