### ISSUE TITLE
Getting Error while installing the project

### ISSUE THREAD

**Issue by jayeshdesai4520** [RocketChat/Apps.Dialogflow#77]
Hello @murtaza98 ,
I am trying to implement the project
I have followed these steps - https://github.com/RocketChat/Apps.Dialogflow
my node version is - v12.16.1
but I am getting this error how can I solve this?
https://imgur.com/SZQPBZQ.jpg

**Comment by murtaza98** [comment]
Hey, @jayeshdesai4520 This seems like some npm package related issue. Try deleting `node_modules/` folder & running `npm i` again. Also, make sure you're on the latest node version and have the `rc-apps` cli up to date
